version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "secretpassword"
    volumes:
      - postgres-data:/var/lib/postgres/data
  app:
    image: ghcr.io/3n-company/geophoto_backend:latest
    environment:
      DB-CONNECTION-STRING: "jdbc:postgresql://postgres:5432/"
      DB-USER: "postgres"
      DB-PASS: "secretpassword"
      SERVER-PORT: 8080
      PHOTO-FOLDER: "/data"
    ports:
      - "8080:8080"
    volumes:
      - app-data:/data
    restart: always

volumes:
    postgres-data:
    app-data:
